# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QPushButton
from PyQt5.QtWidgets import QMessageBox
import sys
from userClass import User
from cameraClass import Camera

from databaseClass import Database
from projectDetails import Ui_projectDetails



class Ui_MainWindow(object):

    def loginUser(self, Dialog):
        usernameEdit = self.usernameEdit.text()
        passwordEdit = self.passwordEdit.text()
        user = User(usernameEdit, passwordEdit)
        loggedIn = user.login()
        print(loggedIn)
        if (loggedIn == True):
            Form.close()
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_projectDetails()
            self.ui.setupUi(self.window)
            self.window.show()


        else:
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("Username or Password is Incorrect\n\nWould you like to try again?")
            msgBox.setWindowTitle("Incorrect Login")
            msgBox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)

            returnValue = msgBox.exec()

            if returnValue == QMessageBox.No:
                QtWidgets.QApplication.closeAllWindows()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginButto = QtWidgets.QPushButton(self.centralwidget)
        self.loginButto.setGeometry(QtCore.QRect(310, 420, 241, 51))
        self.loginButto.setStyleSheet("background-color:rgba(0,25,41,255)\n"
"")
        self.loginButto.setObjectName("loginButto")

        self.loginButto.clicked.connect(self.loginUser)

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(340, 160, 181, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.usernameEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.usernameEdit.setAutoFillBackground(False)
        self.usernameEdit.setStyleSheet("background-color:black;text-color:rgba(232,0,90,255);\n"
"")
        self.usernameEdit.setObjectName("usernameEdit")
        self.gridLayout.addWidget(self.usernameEdit, 0, 0, 1, 1)
        self.passwordEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.passwordEdit.setAutoFillBackground(False)
        self.passwordEdit.setStyleSheet("background-color:rgba(0,25,41,255)\n"
"")
        self.passwordEdit.setObjectName("passwordEdit")
        self.gridLayout.addWidget(self.passwordEdit, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginButto.setText(_translate("MainWindow", "Login"))
        self.usernameEdit.setPlaceholderText("Username")
        self.passwordEdit.setPlaceholderText("Password")
        self.usernameEdit.setText("admin")
        self.passwordEdit.setText("admin")

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()

    sys.exit(app.exec_())

